# Generated by Django 5.0.6 on 2024-07-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhes',
            name='ano_fabricacao_veiculo',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='is_autonomo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='marca_veiculo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='modelo_veiculo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='nome_referencia_comercial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='telefone_comercial',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='telefone_referencia_comercial',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='detalhes',
            name='nome_referencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='detalhes',
            name='telefone_referencia',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
