# Generated by Django 5.0.6 on 2024-07-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhes',
            name='parceiroEmail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='parceiroFullname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
